name: 'Test Sunbeam Extension'
description: 'Test full run of sunbeam extension'
inputs:
  sunbeam-version:
    description: 'Branch or tag of sunbeam to install'
    required: false
    default: 'main'
  extension-full-name:
    description: 'Full name of this extension (e.g. sunbeam-labs/sbx_template or Ulthran/sbx_demic)'
    required: false
    default: ${{ github.event.pull_request.head.repo.full_name }}
  extension-branch-name:
    description: 'Branch name of extension to be tested (e.g. main or 1-feature-branch)'
    required: false
    default: ${{ github.head_ref }}
  other-extensions:
    description: 'Any other extensions needed to run this one (use comma-separated string like "sunbeam-labs/sbx_one,other-user/sbx_two")'
    required: false
    default: ''
  test-directory:
    description: 'Directory that contains e2e tests which need all of sunbeam to run'
    required: false
    default: '.tests/e2e/'
    
runs:
  using: "composite"
  steps:
      - name: setup-conda
        uses: s-weigand/setup-conda@v1.2.4
        with:
          # Additional channels like 'conda-forge' which can be used to install packages
          conda-channels: '' # optional, default is 
      
      - name: Install Sunbeam
        shell: bash
        run: |
          python -m pip install --upgrade pip
          git clone --depth 1 --branch ${{ inputs.sunbeam-version }} https://github.com/sunbeam-labs/sunbeam.git sunbeam
          cd sunbeam
          pip install -e .[dev]
      
      - name: Install Extensions
        shell: bash
        env:
          BRANCH_NAME: ${{ inputs.extension-branch-name }}
          EXTENSION_FULL_NAME: ${{ inputs.extension-full-name }}
          EXTENSIONS_LIST: ${{ inputs.other-extensions }}
        run: |
          if [ -z "${EXTENSION_FULL_NAME}" ]
          then
            URL=${{ github.event.repository.url }}
            ARR=(${URL//// })
            EXTENSION_FULL_NAME="${ARR[-2]}/${ARR[-1]}"
          fi

          echo "BRANCH_NAME: $BRANCH_NAME" >> $GITHUB_STEP_SUMMARY
          echo "EXTENSION_FULL_NAME: $EXTENSION_FULL_NAME" >> $GITHUB_STEP_SUMMARY
          echo "EXTENSIONS_LIST: $EXTENSIONS_LIST" >> $GITHUB_STEP_SUMMARY
          
          for i in ${EXTENSIONS_LIST//,/ }
          do
              sunbeam extend https://github.com/$i
          done

          ARR=(${EXTENSION_FULL_NAME//// })
          EXTENSION_NAME=${ARR[1]}
          
          if [ -z "${BRANCH_NAME}" ]
          then
            git clone https://github.com/$EXTENSION_FULL_NAME extensions/$EXTENSION_NAME
          else
            git clone -b $BRANCH_NAME https://github.com/$EXTENSION_FULL_NAME extensions/$EXTENSION_NAME
          fi
          
      - name: Run Tests
        shell: bash
        run: |
          pytest -vvvv -l --tb=long ${{ inputs.test-directory }} 2>&1 | tee pytest_output.txt
          sed -n '/================================= FAILURES =================================/q;p' pytest_output.txt >> $GITHUB_STEP_SUMMARY
