name: 'Test Sunbeam Extension'
description: 'Test full run of sunbeam extension'
branding:
  icon: 'check-circle'
  color: 'green'
inputs:
  sunbeam-version:
    description: 'Branch or tag of sunbeam to install'
    required: false
    default: 'main'
  other-extensions:
    description: 'Any other extensions needed to run this one (use comma-separated string like "sunbeam-labs/sbx_one,other-user/sbx_two")'
    required: false
    default: ''
  test-directory:
    description: 'Directory that contains e2e tests which need all of sunbeam to run'
    required: false
    default: '.tests/'
  snakefmt-directory:
    description: 'Path to snakefiles for linting'
    required: false
    default: '*.smk'
  black-directory:
    description: 'Path to python files for linting'
    required: false
    default: '.'
    
runs:
  using: "composite"
  steps:
      - name: Setup micromamba
        uses: mamba-org/setup-micromamba@v2
        with:
          environment-name: lockenv
          create-args: python=3.11
          init-shell: bash
          cache-downloads: true
      
      - name: Install Sunbeam
        shell: bash -l {0}
        run: |
          python -m pip install --upgrade pip
          SUNBEAM_SOURCE_DIR="${RUNNER_TEMP:-/tmp}/sunbeam"
          rm -rf "$SUNBEAM_SOURCE_DIR"
          git clone --depth 1 --branch ${{ inputs.sunbeam-version }} https://github.com/sunbeam-labs/sunbeam.git "$SUNBEAM_SOURCE_DIR"
          (
            cd "$SUNBEAM_SOURCE_DIR"
            pip install -e .[dev]
          )
      
      - name: Install extra extensions
        shell: bash -l {0}
        env:
          EXTENSIONS_LIST: ${{ inputs.other-extensions }}
        run: |
          export SUNBEAM_EXTENSIONS=$(dirname "${GITHUB_WORKSPACE}")

          for i in ${EXTENSIONS_LIST//,/ }
          do
              echo "Installing extension: $i" >> $GITHUB_STEP_SUMMARY
              sunbeam extend https://github.com/$i
          done

      - name: Lint
        shell: bash -l {0}
        run: |
          set -euo pipefail
          echo "Snakefmt check..."
          snakefmt --check ${{ inputs.snakefmt-directory }}
          echo "Linted snakefiles: ${{ inputs.snakefmt-directory }}" >> $GITHUB_STEP_SUMMARY
          echo "Black check..."
          black --check --diff ${{ inputs.black-directory }}
          echo "Linted python files: ${{ inputs.black-directory }}" >> $GITHUB_STEP_SUMMARY
          
      - name: Run Tests
        shell: bash -l {0}
        run: |
          export SUNBEAM_EXTENSIONS=$(dirname "${GITHUB_WORKSPACE}")
          echo "Extensions found: $(ls "$SUNBEAM_EXTENSIONS")" >> $GITHUB_STEP_SUMMARY
          pytest -vvvv -l --tb=long "${{ inputs.test-directory }}"
